# Generated by Django 3.2.4 on 2021-06-14 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='актив')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='актив')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('sections', models.ManyToManyField(to='mainapp.Section', verbose_name='разделы')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
