# Generated by Django 3.2.4 on 2021-06-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag', verbose_name='теги'),
        ),
    ]
