# Generated by Django 3.2.4 on 2021-07-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликована'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='отвергнута'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_reviewing',
            field=models.BooleanField(default=False, verbose_name='модерация'),
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='article',
            name='reject_comment',
            field=models.TextField(blank=True, null=True, verbose_name='причина отказа'),
        ),
        migrations.AddField(
            model_name='article',
            name='review_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
    ]
