# Generated by Django 3.2.4 on 2021-07-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210701_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-edited']},
        ),
    ]
