# Generated by Django 3.2.4 on 2021-06-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='забанен до'),
        ),
    ]
