# Generated by Django 3.2.4 on 2021-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Мужской', 'Женский')], max_length=7, verbose_name='пол'),
        ),
    ]
