# Generated by Django 3.2.4 on 2021-07-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='содержимое комментария')),
                ('rating', models.IntegerField(db_index=True, default=0, verbose_name='рейтинг')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='актив')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='статья')),
                ('comment_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentapp.comment', verbose_name='родитель')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
